Repository codeready-toolchain/toolchain-common, pull requests merged in 2019-10, with the labels that each got.

#41 Switch to go 1.13
  README.adoc
  go.mod
Labels: approved, size/XS

#43 chore: use mac compatible --decode
  scripts/add-cluster.sh
Labels: approved, size/XS

#44 chore(CRT-281): add function that ensures KubeFedCluster CRD existence in the cluster
  go.mod
  go.sum
  pkg/cluster/kubefedcluster_crd.go
  pkg/cluster/kubefedcluster_crd_test.go
  pkg/condition/condition_blackbox_test.go
Labels: approved, size/L

#45 Add condition.IsTrue()
  pkg/condition/condition.go
  pkg/condition/condition_blackbox_test.go
Labels: approved, size/M

#46 configure golangci-lint
  .golangci.yml
  make/lint.mk
Labels: approved, size/S
