Repository codeready-toolchain/toolchain-common, pull requests merged in 2019-07, with the labels that each got.

#13 chore: add badges on README
  README.adoc
Labels: size/XS

#15 Add OWNERS
  OWNERS
Labels: lgtm, size/S

#14 Add clean target
  make/clean.mk
Labels: lgtm, size/XS

#16 Add status condition helper functions
  go.mod
  go.sum
  pkg/condition/condition.go
  pkg/condition/condition_blackbox_test.go
  pkg/test/condition.go
Labels: approved, lgtm, size/L

#17 Add condition checkers (to be used by tests)
  pkg/test/condition.go
  pkg/test/condition_test.go
Labels: approved, size/L

#18 Introduce Fake Client (to be used in tests)
  pkg/test/client.go
Labels: approved, size/M

#21 install jq to parse CLONEREF_OPTIONS env var
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm, size/XS

#20 upload coverage reports using OpenShift CI env vars
  .codecov.yaml
  .gitignore
  make/test.mk
Labels: approved, size/M

#23 upload report on PR merge
  make/test.mk
Labels: approved, size/S

#19 Update README.adoc
  README.adoc
Labels: approved, documentation, lgtm, size/M

#24 update IDP configuration parametes
  deploy/idp.yaml
  deploy/user.yaml
Labels: approved, size/XS
