Repository codeready-toolchain/toolchain-common, pull requests merged in 2019-09, with the labels that each got.

#36 FindConditionByType func added
  pkg/condition/condition.go
  pkg/condition/condition_blackbox_test.go
Labels: approved, size/M

#35 chore(CRT-165): move e2e bits to toolchain-e2e repo
  go.mod
  go.sum
  pkg/test/e2e/awaitility.go
  pkg/test/e2e/doubles.go
  pkg/test/e2e/kubefed.go
Labels: approved, size/L

#37 add var and func to get host and member clusters
  pkg/cluster/cache.go
  pkg/cluster/cache_whitebox_test.go
Labels: approved, size/M

#38 Fix flaky cluster cache test
  pkg/cluster/cache_whitebox_test.go
Labels: approved, size/XS

#39 align type name
  README.adoc
  pkg/test/masteruserrecord/doubles.go
Labels: approved, size/S

#40 update to latest github.com/codeready-toolchain/api
  go.mod
  go.sum
  pkg/test/masteruserrecord/doubles.go
Labels: approved, size/L
