Repository codeready-toolchain/toolchain-common, pull requests merged in 2019-08, with the labels that each got.

#22 chore: create kubefedcluster cr for cluster to register itself as host and member
  README.adoc
  scripts/add-cluster.sh
Labels: approved, size/L

#25 remove shift from -s as it's single params
  scripts/add-cluster.sh
Labels: approved, lgtm, size/XS

#26 find short cluster name from infrastructure CRD
  scripts/add-cluster.sh
Labels: approved, lgtm, size/S

#27 fix cluster_join_to_name variable length
  scripts/add-cluster.sh
Labels: approved, lgtm, size/S

#28 feat(CRT-165,CRT-202): add skeleton for KubeFedCluster e2e test & add test doubles for running e2e test with both operators
  go.mod
  go.sum
  pkg/test/e2e/awaitility.go
  pkg/test/e2e/doubles.go
  pkg/test/e2e/kubefed.go
Labels: approved, size/L

#29 feat: add controller client to Awaitility to be able to run status requests
  pkg/test/e2e/awaitility.go
  pkg/test/e2e/kubefed.go
Labels: approved, size/S

#30 feat(test): add status update mock to fake client
  pkg/test/client.go
Labels: approved, size/S

#31 Added KubeClient to Awaitility
  go.mod
  go.sum
  pkg/test/e2e/awaitility.go
  pkg/test/e2e/kubefed.go
Labels: approved, size/L

#32 Add Get and List to fake client
  pkg/test/client.go
  pkg/test/client_test.go
Labels: approved, size/L

#33 fix: watch KubeFedCluster only within operator namespace
  pkg/controller/kubefedcluster_caching.go
Labels: approved, size/XS

#34 chore: move custom assertions and doubles from host-operator repo
  go.mod
  go.sum
  pkg/test/doubles.go
  pkg/test/masteruserrecord/assertion.go
  pkg/test/masteruserrecord/doubles.go
  pkg/test/useraccount/assertion.go
  pkg/test/useraccount/doubles.go
Labels: approved, size/L
