Repository codeready-toolchain/toolchain-common, pull requests merged in 2019-12, with the labels that each got.

#64 chore(CRT-356): move template.Processor logic from member and support comparison of objects
  go.mod
  go.sum
  pkg/template/filter.go
  pkg/template/filter_test.go
  pkg/template/processor.go
  pkg/template/processor_test.go
Labels: approved, size/XXL

#65 Remove deprecated TargetCluster from MUR status
  go.mod
  go.sum
  pkg/test/masteruserrecord/assertion.go
Labels: approved, size/S

#63 Added temporary fix for token timestamp issue
  pkg/test/auth/tokenmanager.go
  pkg/test/auth/tokenmanager_test.go
Labels: approved, size/L

#68 overriding sub and nbf claims
  pkg/test/auth/tokenmanager.go
  pkg/test/auth/tokenmanager_test.go
Labels: approved, size/M

#69 chore: make functions helping with creation of template publicly available
  pkg/template/processor_test.go
  pkg/test/template.go
Labels: approved, size/L

#70 feat: add functions for easy (un)setting variables in a test
  go.mod
  go.sum
  pkg/test/env.go
  pkg/test/env_test.go
Labels: approved, size/L
