Repository codeready-toolchain/toolchain-common, pull requests merged in 2019-11, with the labels that each got.

#47 adding tokenmanager and related tests to common
  .codecov.yaml
  pkg/test/auth/tokenmanager.go
  pkg/test/auth/tokenmanager_test.go
Labels: approved, size/L

#49 Switch to go 1.13 in builder image
  openshift-ci/Dockerfile.tools
Labels: approved, size/S

#50 Fix Dokerfile.tools
  openshift-ci/Dockerfile.tools
Labels: approved, size/XS

#48 Switch to Kube 1.14
  go.mod
  go.sum
  pkg/cluster/kubefedcluster_crd_test.go
  pkg/test/client.go
  pkg/test/client_test.go
Labels: approved, size/XL

#52 Update KubeFedCluster CRD
  go.mod
  go.sum
  pkg/cluster/kubefedcluster.go
  pkg/cluster/kubefedcluster_assets.go
  pkg/cluster/kubefedcluster_crd.go
  pkg/cluster/kubefedcluster_test.go
Labels: approved, size/XL

#54 chore: update KubeFed group in add-cluster.sh script
  scripts/add-cluster.sh
Labels: approved, size/XS

#53 e2e hard-coded jwk
  go.mod
  go.sum
  pkg/test/auth/tokenmanager.go
  pkg/test/auth/tokenmanager_test.go
Labels: approved, size/L

#55 chore: delete secret if exists when registering a cluster
  scripts/add-cluster.sh
Labels: approved, size/XS

#57 chore: support separated clusters when registering host and member
  README.adoc
  scripts/add-cluster.sh
Labels: approved, size/M

#56 Add APIEndpoint to FedCluster
  pkg/cluster/cache.go
  pkg/cluster/service.go
  pkg/cluster/service_test.go
Labels: approved, size/S

#59 overriding iat time
  pkg/test/auth/tokenmanager.go
  pkg/test/auth/tokenmanager_test.go
Labels: approved, size/S

#58 add kubeconfig option to avoid prompt
  README.adoc
  scripts/add-cluster.sh
Labels: approved, size/M

#60 adding exp extra claim
  pkg/test/auth/tokenmanager.go
  pkg/test/auth/tokenmanager_test.go
Labels: approved, size/S

#61 Switch to Cluster in UserAccount Embeded Status
  go.mod
  go.sum
  pkg/test/masteruserrecord/assertion.go
Labels: approved, size/S

#62 fix: refresh cluster cach when a cluster is not found
  pkg/cluster/cache.go
  pkg/cluster/cache_whitebox_test.go
  pkg/cluster/kubefedcluster_assets.go
  pkg/cluster/service.go
  pkg/cluster/service_test.go
  pkg/cluster/service_whitebox_test.go
  pkg/controller/kubefedcluster_caching.go
  pkg/test/client.go
  pkg/test/cluster.go
Labels: approved, size/L
