Repository codeready-toolchain/toolchain-common, pull requests merged in 2020-02, with the labels that each got.

#74 chore: move ApplySingle to separated struct
  pkg/client/client.go
  pkg/client/client_test.go
  pkg/template/processor.go
  pkg/template/processor_test.go
Labels: approved, size/XL

#75 Update to latest API
  go.mod
  go.sum
  pkg/cluster/kubefedcluster_test.go
  pkg/test/masteruserrecord/doubles.go
  pkg/test/useraccount/doubles.go
Labels: approved, size/M

#76 Deprecating Embedded UA ID/Disabled
  pkg/test/useraccount/assertion.go
  pkg/test/useraccount/doubles.go
Labels: approved, size/S

#78 Assertion for userid and disabled
  pkg/test/useraccount/assertion.go
Labels: approved, size/XS

#79 updating api to version deprecating userid and disabled fields from U…
  go.mod
  go.sum
  pkg/test/masteruserrecord/doubles.go
Labels: approved, size/S

#80 Updating api version
  go.mod
  go.sum
Labels: approved, size/XS

#81 Update to Kube 1.16.2
  go.mod
  go.sum
  pkg/cluster/kubefedcluster_assets.go
  pkg/cluster/kubefedcluster_test.go
  pkg/test/client_test.go
Labels: approved, size/XL

#83 Update to latest API
  go.mod
  go.sum
Labels: approved, size/M

#82 Disable mur
  pkg/condition/condition.go
  pkg/condition/condition_blackbox_test.go
  pkg/test/masteruserrecord/doubles.go
Labels: approved, size/M
