Repository codeready-toolchain/toolchain-common, pull requests merged in 2020-03, with the labels that each got.

#84 Uamodifier to disable spec
  pkg/test/masteruserrecord/doubles.go
  pkg/test/useraccount/doubles.go
Labels: size/XS

#85 renaming doubles
  pkg/test/masteruserrecord/master_user_record.go
  pkg/test/useraccount/user_account.go
Labels: approved, size/XS

#87 feat: add assertions to check tier in MUR
  go.mod
  go.sum
  pkg/test/masteruserrecord/assertion.go
Labels: approved, size/M

#88 fix test on updating resource
  pkg/client/client.go
  pkg/client/client_test.go
Labels: approved, size/L

#89 Update Generation in Fake client
  go.mod
  go.sum
  pkg/client/client_test.go
  pkg/test/client.go
  pkg/test/client_test.go
Labels: approved

#90 include ClusterResources in MUR (in tests)
  go.mod
  go.sum
  pkg/cluster/kubefedcluster_assets.go
  pkg/test/client.go
  pkg/test/condition.go
  pkg/test/masteruserrecord/assertion.go
  pkg/test/masteruserrecord/master_user_record.go
  pkg/test/masteruserrecord/master_user_record_test.go
  pkg/test/testing_t.go
Labels: approved

#91 add NSTemplateSet fluent assertions
  pkg/test/masteruserrecord/assertion.go
  pkg/test/nstemplateset/assertion.go
Labels: approved

#93 Revert "add NSTemplateSet fluent assertions (#91)"
  pkg/test/masteruserrecord/assertion.go
  pkg/test/nstemplateset/assertion.go
Labels: approved
